---
- hosts: bakery
  user: "{{ user }}"
  become: yes
  vars:
    tmzone: America/Vancouver
    sudo_timeout: 20
    ssh_port: 22
  roles: 
    - setup
    - docker

- hosts: servers, k8s_pis
  user: "{{ user }}"
  become: yes
  roles: 
    - role: istvano.microk8s
      vars:
        microk8s_group_HA: servers
        microk8s_group_WORKERS: k8s_pis
