---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: hyperv
platforms: 
  - name: ubuntu
    groups:
      - linux
    instance_raw_config_args:
      - 'vm.network "private_network", bridge: "External Switch"'
    box: generic/ubuntu2204
    box_url: "generic/ubuntu2204"
    memory: 2048
    cpus: 2
provisioner:
  name: ansible 
  options:
    vvv: True
  inventory:
    host_vars:
      example: example
  playbooks:
    prepare: prepare.yml
verifier:
  name: inspec