---
# tasks file for microk8s

- name: Enable cgroups
  lineinfile:
    dest: "/boot/firmware/cmdline.txt"
    insertafter: EOF
    line: "cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1"
    state: present
  become: true

- name: Install microk8s
  community.general.snap:
    name: microk8s
    classic: true
    channel: 1.26

- name: Ensure that Ubuntu RPi software package is installed
  apt:
    pkg:
      - linux-modules-extra-raspi
    state: latest
  become: true

- name: Check if reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required
  become: true

- name: Reboot the server if needed
  reboot:
    msg: "Reboot initiated by Ansible because of reboot required file."
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  when: reboot_required.stat.exists
  become: true