---
- name: Pre-run setup
  include_tasks: pre.yaml

- name: Ubuntu updates and package installs
  include_tasks: ubuntu.yaml

- name: Pi-specific config
  include_tasks: pi.yaml
  when: uname.stdout | regex_search('raspi')

- name: System config
  include_tasks: system.yaml

- name: Firewall config
  include_tasks: firewall.yaml
  when: uname.stdout | regex_search('raspi')

- name: Post-run setup
  include_tasks: post.yaml