---
# tasks file for setup
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yaml"

- name: Get datestamp from the system
  shell: date +"%Y%m%d"
  register: dstamp

- name: Set current date stamp variable
  set_fact:
    cur_date: "{{ dstamp.stdout }}"

# Update and install the base software
- name: Update apt package cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Upgrade installed apt packages 
  apt:
    upgrade: dist
  register: upgrade
  retries: 15
  delay: 5
  until: upgrade is success
  become: yes

- name: Ensure that these software packages are installed
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - git
      - nano
      - needrestart
      - pwgen
      - python3-pip
      - python3-setuptools
      - software-properties-common
      - unbound
      - unzip
      - virtualenv
      - wget
    state: latest
  become: yes

# Host Setup
#- name: Set static hostname
#  hostname:
#    name: "{{ inventory_hostname_short }}"
#  become: yes
#
#- name: Add FQDN to /etc/hosts
#  lineinfile:
#    dest: /etc/hosts
#    regexp: '^127\.0\.0\.1'
#    line: '127.0.0.1 {{ inventory_hostname }} {{ inventory_hostname_short }}'
#    state: present
#  become: yes

- name: set timezone
  timezone:
    name: "{{ tmzone }}"
  become: yes

# Set sudo password timeout (default is 15 minutes)
- name: Set sudo password timeout.
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^Defaults\tenv_reset'
    line: 'Defaults env_reset, timestamp_timeout={{ sudo_timeout }}'
    validate: '/usr/sbin/visudo -cf %s'
  become: yes

- name: Create/update regular user with sudo privileges
  user:
    name: "{{ user }}"
    password: "{{ user_password }}"
    state: present
    groups: sudo
    append: true
    shell: /bin/bash
  become: yes

- name: Ensure authorized keys for remote user is installed
  authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ public_key }}"
  become: yes

- name: Disable password authentication for root
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin prohibit-password'
  notify:
    - restart sshd
  become: yes

- name: Disable tunneled clear-text passwords
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication no'
  notify:
    - restart sshd
  become: yes

- name: Set user PS1 to a two-line prompt
  lineinfile:
    dest: "/home/{{ user }}/.bashrc"
    insertafter: EOF
    line: "PS1='${debian_chroot:+($debian_chroot)}\\[\\033[01;32m\\]\\u@\\h\\[\\033[00m\\]:\\[\\033[01;34m\\]\\w\\[\\033[00m\\]\\n\\$ '"
    state: present
  become: yes

- name: Set root PS1 to a two-line prompt
  lineinfile:
    path: '/root/.bashrc'
    state: present
    insertafter: EOF
    line: PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\n\$ '
  become: yes

# Configure a firewall
- name: Disable and reset ufw firewall to installation defaults.
  ufw:
    state: reset
  become: yes

- name: Find backup rules to delete
  find:
    paths: /etc/ufw
    patterns: "*.{{ cur_date }}_*"
    use_regex: no
  register: files_to_delete
  become: yes

- name: Delete ufw backup rules
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ files_to_delete.files }}"
  become: yes

- name: Allow ssh port '{{ ssh_port }}'.
  ufw:
    rule: allow
    proto: tcp
    port: '{{ ssh_port }}'
    state: enabled
  become: yes

- name: Turn UFW logging off
  ufw:
    logging: "off"
  become: yes

- name: Check if reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required
  become: yes

- name: Reboot the server if needed
  reboot:
    msg: "Reboot initiated by Ansible because of reboot required file."
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  when: reboot_required.stat.exists
  become: yes

- name: Remove old packages from the cache
  apt:
    autoclean: yes
  become: yes

- name: Remove dependencies that are no longer needed
  apt:
    autoremove: yes
    purge: yes
  become: yes