---
- name: Check if a reboot is needed for Debian-based systems
  stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: run needrestart
  command: needrestart -r a
  when: not reboot_required.stat.exists and upgrade.changed

- name: Reboot the server if needed
  reboot:
    msg: "Reboot initiated by Ansible because of reboot required file."
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  when: reboot_required.stat.exists

- name: Mark first run complete
  when: not already_bootstrapped.stat.exists
  shell: touch /var/run/bootstrapped
  